#!/bin/sh
#
# batteryd -- Monitor battery, beep if low.
#             Run by /etc/systemd/system/batteryd.service .
#             Assumes there is a 'beep' program available.
#
LOW_LEVEL=20
while :; do
    capacity="$(cat /sys/class/power_supply/BAT/capacity)"
    online="$(cat /sys/class/power_supply/AC/online)"
    if [ "$capacity" -le "$LOW_LEVEL"  -a  "$online" -ne "1" ]; then 
        beep; beep; beep; sleep 2
    else
        sleep 30
    fi
done
